trigger:
- none

strategy:
  matrix:
    'Ubuntu 16.04':
      image: 'ubuntu-16.04'
      dotnetcore: '2.2.x'
    'Ubuntu 18.04':
      image: 'ubuntu-18.04'
      dotnetcore: '3.1.x'
  

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: echo $(image) $(dotnetcore)
    displayName: 'echo command'