trigger:
  - none

variables:
  - name: variableFiles
    value: |
      variables1.yaml
      variables2.yaml

jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        variables1: { variableFile: 'variables1.yaml' }
        variables2: { variableFile: 'variables2.yaml' }
    steps:
      # - template: $(variableFile)  # Use the variable file for each matrix entry
      - script: |
          echo "Printing variables from $(variableFile)"
          echo "variable1: $(variable1)"
          echo "variable2: $(variable2)"
          echo "variable3: $(variable3)"
          echo "variable4: $(variable4)"
        displayName: 'Print variables'
