trigger: none

stages:
- stage: BuildStage
  jobs:
  - job: RunWithVariables
    strategy:
      matrix:
        variablesSet1:
          variableFile: variables1.yaml
        variablesSet2:
          variableFile: variables2.yaml
    template: joby.yaml
    parameters:
      variableFile: ${{ matrix.variableFile }}
